/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateTime = IDL.Record({
  'day' : IDL.Int,
  'month' : IDL.Nat,
  'hour' : IDL.Int,
  'year' : IDL.Int,
  'minute' : IDL.Int,
  'second' : IDL.Int,
});
export const RecordType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const FinancialRecord = IDL.Record({
  'id' : IDL.Nat,
  'date' : DateTime,
  'description' : IDL.Text,
  'category' : RecordType,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [DateTime, IDL.Text, IDL.Float64, RecordType],
      [IDL.Nat],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getRecords' : IDL.Func([], [IDL.Vec(FinancialRecord)], ['query']),
  'getRecordsSortedByDate' : IDL.Func(
      [],
      [IDL.Vec(FinancialRecord)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateTime = IDL.Record({
    'day' : IDL.Int,
    'month' : IDL.Nat,
    'hour' : IDL.Int,
    'year' : IDL.Int,
    'minute' : IDL.Int,
    'second' : IDL.Int,
  });
  const RecordType = IDL.Variant({ 'expense' : IDL.Null, 'income' : IDL.Null });
  const FinancialRecord = IDL.Record({
    'id' : IDL.Nat,
    'date' : DateTime,
    'description' : IDL.Text,
    'category' : RecordType,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [DateTime, IDL.Text, IDL.Float64, RecordType],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getRecords' : IDL.Func([], [IDL.Vec(FinancialRecord)], ['query']),
    'getRecordsSortedByDate' : IDL.Func(
        [],
        [IDL.Vec(FinancialRecord)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };