/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DateTime {
  'day' : bigint,
  'month' : bigint,
  'hour' : bigint,
  'year' : bigint,
  'minute' : bigint,
  'second' : bigint,
}
export interface FinancialRecord {
  'id' : bigint,
  'date' : DateTime,
  'description' : string,
  'category' : RecordType,
  'amount' : number,
}
export type RecordType = { 'expense' : null } |
  { 'income' : null };
export interface _SERVICE {
  'addRecord' : ActorMethod<[DateTime, string, number, RecordType], bigint>,
  'deleteRecord' : ActorMethod<[bigint], undefined>,
  'getRecords' : ActorMethod<[], Array<FinancialRecord>>,
  'getRecordsSortedByDate' : ActorMethod<[], Array<FinancialRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];